<a href="https://colab.research.google.com/github/jahnavimidde/VsemML/blob/main/Lab1ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s=pd.Series(['A,','B','C'])
print(s)


0    A,
1     B
2     C
dtype: object


In [ ]:
#9
import pandas as pd
df = pd.DataFrame({
    2014: [1, 2, 3, 4, 5],
    2015: [1, 12.3, 45.5, 78273, 56],
    2016: [1, 3, 7, 44, 33],
    2017: [1, 12.3, 45.5, 78273, 56],
    2018: [1, 3, 7, 44, 33]
}, index=['Madhu', 'Kusum', 'john', 'Ankit', 'Shruthi'])
print(df)

#10
print(df.index)
print(df.columns)
print(df.dtypes)

print(df.ndim)
print(df.shape)
print(df.size)
print(df.values)
print(df.tail(2))
print(df.iloc[:,:2])

data = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}
print(data)
df2 = pd.DataFrame({
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
})
print(df2)
print(df2.empty)

#11
df[2018] = df2['2018']
print(df)
print(df.T)
print(df[2017])
print(df.loc[df.index.intersection(['Madhu', 'Sumeet']), [2017, 2018]])
print(df.index)
print(df.columns)
print(df.loc[['Shruthi'], [2016]])

# Add Sumeet's sales data
df.loc['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]

# Drop 3rd row
df = df.drop(df.index[2])
print(df)



print(df2.drop(df.index[2]))



         2014     2015  2016     2017  2018
Madhu       1      1.0     1      1.0     1
Kusum       2     12.3     3     12.3     3
john        3     45.5     7     45.5     7
Ankit       4  78273.0    44  78273.0    44
Shruthi     5     56.0    33     56.0    33
Index(['Madhu', 'Kusum', 'john', 'Ankit', 'Shruthi'], dtype='object')
Index([2014, 2015, 2016, 2017, 2018], dtype='int64')
2014      int64
2015    float64
2016      int64
2017    float64
2018      int64
dtype: object
2
(5, 5)
25
[[1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00]
 [2.0000e+00 1.2300e+01 3.0000e+00 1.2300e+01 3.0000e+00]
 [3.0000e+00 4.5500e+01 7.0000e+00 4.5500e+01 7.0000e+00]
 [4.0000e+00 7.8273e+04 4.4000e+01 7.8273e+04 4.4000e+01]
 [5.0000e+00 5.6000e+01 3.3000e+01 5.6000e+01 3.3000e+01]]
         2014     2015  2016     2017  2018
Ankit       4  78273.0    44  78273.0    44
Shruthi     5     56.0    33     56.0    33
         2014     2015
Madhu       1      1.0
Kusum       2     12.3
john        3  

In [ ]:
print(df2.drop('Kinshuk'))
#Change the name of the salesperson Ankit to
#Vivaan and Madhu to Shailesh.
#rename uses index and columns
print(df.rename(index={'Madhu':'Shailesh','Ankit':'Vivaan'},inplace=True))
df.loc['Shailesh',2018]=10000
print(df)
df = df.drop(['Shailesh', 'shailesh'], errors='ignore')






          2018
Madhu   160000
Kusum   110000
Ankit   340000
Shruti  900000
None
           2014     2015     2016     2017      2018
Kusum       2.0     12.3      3.0     12.3  110000.0
Vivaan      4.0  78273.0     44.0  78273.0  340000.0
Shruthi     5.0     56.0     33.0     56.0       NaN
Sumeet    196.2  37800.0  52000.0  78438.0   38852.0
Shailesh    NaN      NaN      NaN      NaN   10000.0


In [ ]:

import pandas as pd
df.to_csv('SalesFigures.csv',index=False,header=False)
reading=pd.read_csv('SalesFigures.csv',header=None)# pandas automatically understands the first row as header
reading.index=df.index
reading.columns=df.columns
print(reading)

          2014     2015     2016     2017      2018
Kusum      2.0     12.3      3.0     12.3  110000.0
Vivaan     4.0  78273.0     44.0  78273.0  340000.0
Shruthi    5.0     56.0     33.0     56.0       NaN
Sumeet   196.2  37800.0  52000.0  78438.0   38852.0


In [ ]:
import pandas as pd

data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

df = pd.DataFrame(data)


print(df)
new_rows = pd.DataFrame([
    {"Item": "TV", "Company": "SAMSUNG", "Rupees": 13000, "USD": 720},
    {"Item": "AC", "Company": "SONY", "Rupees": 16000, "USD": 790}
])
df = pd.concat([df, new_rows], ignore_index=True)
print(df)
#max price lg tv
print(df[(df['Item']=='TV')&(df['Company']=='LG')]['Rupees'].max())
print(sum(df['Rupees']))
print(df[(df['Company']=='SONY')]['USD'].median())



  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV   SAMSUNG   13000  720
5   AC      SONY   16000  790
15000
80000
770.0


In [ ]:
import pandas as pd


data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krrishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', None, 'BCA', 'MBA'],
    'Score': [90.0, None, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df3 = pd.DataFrame(data)
print(df3)
print(df3.groupby("Degree")["Score"].max())
df['Score'].fillna(76)
print(df)
#df.set_index('Name')
#print(df)
# Group by Name and Degree, then calculate average Score
average_marks = df.groupby([df.index, 'Degree'])['Score'].mean()
print(average_marks)
print(df[df['Degree']=='MBA'].count())
print(len(df[df['Degree']=='MBA']))
print(df[df['Degree'] == 'BCA']['Score'].mode())








        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA    NaN
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen    None   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0
Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64
           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA   76.0
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen       None   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0
Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Pankaj     BCA       76.0
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64
Degree    3
Score     3
dtype: int64
3
0    76.0
1    78.0
Name: Score, dtype: float64


In [ ]:
import numpy as np


column_names = ['mpg', 'cylinders', 'displacement', 'horsepower',
                'weight', 'acceleration', 'model_year', 'origin', 'car_name']

# Load dataset
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
df=pd.read_csv(url,delim_whitespace=True,names=column_names,na_values="?")
print(df.describe(include="all"))

print(df.head(10))
print(df.ffill())
print(df.isnull().sum())
print(df.dropna())



/tmp/ipython-input-10-3439570444.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df=pd.read_csv(url,delim_whitespace=True,names=column_names,na_values="?")


               mpg   cylinders  displacement  horsepower       weight  \
count   398.000000  398.000000    398.000000  392.000000   398.000000   
unique         NaN         NaN           NaN         NaN          NaN   
top            NaN         NaN           NaN         NaN          NaN   
freq           NaN         NaN           NaN         NaN          NaN   
mean     23.514573    5.454774    193.425879  104.469388  2970.424623   
std       7.815984    1.701004    104.269838   38.491160   846.841774   
min       9.000000    3.000000     68.000000   46.000000  1613.000000   
25%      17.500000    4.000000    104.250000   75.000000  2223.750000   
50%      23.000000    4.000000    148.500000   93.500000  2803.500000   
75%      29.000000    8.000000    262.000000  126.000000  3608.000000   
max      46.600000    8.000000    455.000000  230.000000  5140.000000   

        acceleration  model_year      origin    car_name  
count     398.000000  398.000000  398.000000         398  
uniqu

In [ ]:
max_mpg=(df['mpg'].max())
b=df[df['mpg']==max_mpg]
print(b[:])
print(df.groupby('cylinders')['displacement'].mean())
print(df['cylinders'].mean())
print(df[df['weight']>= df['weight'].mean()]['car_name'].count())


      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0  2110.0          17.9   

     model_year  origin   car_name  
322          80       3  mazda glc  
cylinders
3     72.500000
4    109.796569
5    145.000000
6    218.142857
8    345.009709
Name: displacement, dtype: float64
5.454773869346734
171
